import {
	Box,
	Utensils,
	ShoppingBag,
	Car,
	House,
	Briefcase,
	HeartPulse,
	Film,
	Zap,
	GraduationCap,
	Plane,
	Gift,
	PiggyBank,
	TrendingUp,
	Wallet,
	CreditCard,
	Coins,
	Building,
	Receipt,
	Wrench,
	type LucideIcon,
} from 'lucide-react'

const categoryIcons: { name: string; icon: LucideIcon; }[] = [
	{ name: 'box',						icon: Box },
	{ name: 'utensils',				icon: Utensils },
	{ name: 'shopping-bag',		icon: ShoppingBag },
	{ name: 'car',						icon: Car },
	{ name: 'house',					icon: House },
	{ name: 'briefcase',			icon: Briefcase },
	{ name: 'heart-pulse',		icon: HeartPulse },
	{ name: 'film',						icon: Film },
	{ name: 'zap',						icon: Zap },
	{ name: 'graduation-cap',	icon: GraduationCap },
	{ name: 'plane',					icon: Plane },
	{ name: 'gift',						icon: Gift },
	{ name: 'piggy-bank',			icon: PiggyBank },
	{ name: 'trending-up',		icon: TrendingUp },
	{ name: 'wallet',					icon: Wallet },
	{ name: 'credit-card',		icon: CreditCard },
	{ name: 'coins',					icon: Coins },
	{ name: 'building',				icon: Building },
	{ name: 'receipt',				icon: Receipt },
	{ name: 'wrench',					icon: Wrench },
];

export default categoryIcons;